### ISSUE TITLE
ttrss 日志报错

### ISSUE THREAD

**Issue by MuXia-0326** [Colin-XKL/RSSmanX#12]
请问如何解决

```sh
[root@VM-12-4-centos RSSmanX]# docker logs ttrss
PDOException: SQLSTATE[08006] [7] connection to server at "database.ttrss" (172.19.0.4), port 5432 failed: FATAL:  database "ttrss" does not exist in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(81): checkConnection()
#3 {main}Database not found, creating.
Database table not found, applying schema...
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
PHP Parse error:  syntax error, unexpected identifier "pass_for_DB", expecting ")" in /var/www/config.php on line 7
```

**Comment by Colin-XKL** [comment]
看日志是连接数据库时出了问题，需要检查你填写的 ttrss 和 ttrss_db 的数据库名称、账号密码是否一致，以及是否有特殊字符等，检查一下你的 docker-compose 文件以及.env 文件

**Comment by MuXia-0326** [comment]
> 看日志是连接数据库时出了问题，需要检查你填写的 ttrss 和 ttrss_db 的数据库名称、账号密码是否一致，以及是否有特殊字符等，检查一下你的 docker-compose 文件以及.env 文件

我的.env文件是这样的 docker-compose 文件就是 项目里面的 [docker-compose-ultimate.yml](https://github.com/Colin-XKL/RSSmanX/blob/master/docker-compose-ultimate.yml)

```sh
# 数据库密码，不填则使用默认值
DB_Password=

# 自定义数据库存储路径，末尾不需要斜杠。不填则默认使用~/.docker
DB_DIR=/data/docker

# 你的服务器绑定的域名或者是IP
HOST= ip

# 指定Huginn绑定的外部端口
HUGINN_PORT=14000

# 指定TTRSS绑定的外部端口
TTRSS_PORT=13000

# TTRSS订阅RSS的白名单端口，留空则默认接受80和443
RSS_ALLOEW_PORTS=80,443,3000,7000

# 指定TTRSS的SELF URL，类似http://my.domain.com:1212
# my.domain.com替换为你的域名，如没有填写IP即可
# 安装完成后通过设置的SELF URL访问你的TTRSS服务
TTRSS_SELF_URL=http://ip:13000

# -----------------------------------------------
# 安装完成后通过设置的SELF URL访问你的TTRSS服务
# 安装完成后通过http://<HOST>:<HUGINN_PORT>访问你的Huginn服务，替换变量去掉括号
```

**Comment by Colin-XKL** [comment]
测了一下，是默认密码的问题，docker 加载的时候最终读取的到默认密码多了引号，ttrss 那边解析的时候出错了。自定密码的时候不会触发这个问题，目前主仓库的compose 文件里默认密码设置已经去掉引号，应该没问题了

**Comment by MuXia-0326** [comment]
> 测了一下，是默认密码的问题，docker 加载的时候最终读取的到默认密码多了引号，ttrss 那边解析的时候出错了。自定密码的时候不会触发这个问题，目前主仓库的compose 文件里默认密码设置已经去掉引号，应该没问题了

好的，谢谢
