### ISSUE TITLE
安装后ttrss跑不起来

### ISSUE THREAD

**Issue by MuXia-0326** [Colin-XKL/RSSmanX#14]
日志信息如下，麻烦作者大大看一下
```sh
[root@VM-12-4-centos RSSmanX]# docker logs ttrss
PDOException: SQLSTATE[08006] [7] connection to server at "database.ttrss" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.ttrss" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.ttrss" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.ttrss" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.ttrss" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.ttrss" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
Stack trace:
#0 /initialize.php(163): PDO->__construct()
#1 /initialize.php(172): connectDatabase()
#2 /initialize.php(74): checkConnection()
#3 {main}PDOException: SQLSTATE[08006] [7] connection to server at "database.ttrss" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres" in /initialize.php:163
```

**Comment by Colin-XKL** [comment]
日志信息写的 password authentication failed，应该是密码问题。需要检查一下密码配置的方式，以及ttrss和ttrss_db那边密码设定是否一致

**Comment by MuXia-0326** [comment]
我只修改了.env文件配置，yml配置文件没动，用的项目内的

**Comment by Colin-XKL** [comment]
继续排查需要更多信息，使用的哪个版本的yml文件，env里面是使用的自定义的密码还是留空使用的默认密码，以及是不是拉取的最新版本的代码，最近仓库代码有变更如果使用的旧版本可能会遇到预期之外的问题

**Comment by MuXia-0326** [comment]
> 继续排查需要更多信息，使用的哪个版本的yml文件，env里面是使用的自定义的密码还是留空使用的默认密码，以及是不是拉取的最新版本的代码，最近仓库代码有变更如果使用的旧版本可能会遇到预期之外的问题

使用的docker-compose-ultimate.yml版本

密码留空和设置都试了，都是一样的报错信息

使用的是最新的代码

**Comment by Colin-XKL** [comment]
突然想起来前几天那个issue应该也是你提交的，那个时候你使用的老版本有问题的yml文件启动了一次，使用的默认密码，由于数据库类型的应用默认是配置了数据持久化，数据保存在磁盘上，容器销毁后保存在磁盘上的数据并不会自动清除，后续你启动新的数据库容器仍然会尝试从硬盘读取文件。

**Comment by MuXia-0326** [comment]
那保存在硬盘的数据在什么位置，我去删除了重新试试

**Comment by Colin-XKL** [comment]
所以你需要删除磁盘上的数据库持久化的文件，再重新启动数据库容器，这样你新配置的密码才会生效。否则每次启动使用的都是之前的配置生成的数据库，数据库的密码还是之前的，你在配置文件里让ttrss用新的密码去连接老的密码的数据库当然不通了

默认的数据库文件在`~/.docker/Database`下面，ttrss的数据库的文件夹为DBttrss，huginn同理

**Comment by MuXia-0326** [comment]
好的，删除后试试

**Comment by MuXia-0326** [comment]
已经成功部署了，感谢作者的解答，谢谢

**Comment by MuXia-0326** [comment]
作者大大又有一个新问题，就是订阅无法获取内容

下面是调试订阅源的日志
```
[08:53:24/38] start
[08:53:24/38] running HOOK_FETCH_FEED handlers...
[08:53:24/38] feed data has not been modified by a plugin.
[08:53:24/38] local cache will not be used for this feed
[08:53:24/38] last unconditional update request: 
[08:53:24/38] maximum allowed interval for conditional requests exceeded, forcing refetch
[08:53:24/38] fetching https://github.com/Womsxd/AutoMihoyoBBS/commits/master.atom (force_refetch: 1)...
[08:53:24/38] fetch done.
[08:53:24/38] effective URL (after redirects): https://github.com/Womsxd/AutoMihoyoBBS/commits/master.atom (IP: 20.205.243.166) 
[08:53:24/38] server last modified: 
[08:53:24/38] unable to fetch: ; 7 Failed to connect to clash port 8080 after 0 ms: Connection refused [0]
```

**Comment by MuXia-0326** [comment]
这个是不是clash 配置文件 config.yaml 规则编写问题？

**Comment by Colin-XKL** [comment]
Failed to connect to clash port 8080 , 是连接clash的时候出问题了，需要检查下clash的日志有没有异常情况

**Comment by MuXia-0326** [comment]
我知道了，我自己改了一下config.yaml的内容，可能跟你原有的配置冲突了，我重新弄下clash试试

**Comment by MuXia-0326** [comment]
想问下，如果想换自己的节点的话，这个clash 的 配置文件应该如何改动

**Comment by Colin-XKL** [comment]
clash 相关的配置可参考[clash wiki](https://github.com/Dreamacro/clash/wiki/Configuration)，添加你自己的节点到clash字段，在最底下rules字段配置特定规则的站点走你自定义的节点就好

**Comment by MuXia-0326** [comment]
好的
