### ISSUE TITLE
huginn 外网无法访问，启动报错

### ISSUE THREAD

**Issue by caoliang12121** [Colin-XKL/RSSmanX#21]
foreman stdout | 10:09:53 web.1  | /usr/local/lib/ruby/3.2.0/socket.rb:205:in `bind': Permission denied - bind(2) for 0.0.0.0:80 (Errno::EACCES)
foreman stdout | 10:09:53 web.1  | 	from /usr/local/lib/ruby/3.2.0/socket.rb:205:in `listen'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /usr/local/lib/ruby/3.2.0/socket.rb:768:in `block in tcp_server_sockets'
foreman stdout | 10:09:53 web.1  | 	from /usr/local/lib/ruby/3.2.0/socket.rb:231:in `each'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /usr/local/lib/ruby/3.2.0/socket.rb:231:in `foreach'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /usr/local/lib/ruby/3.2.0/socket.rb:766:in `tcp_server_sockets'
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/webrick-1.8.1/lib/webrick/utils.rb:60:in `create_listeners'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/webrick-1.8.1/lib/webrick/server.rb:130:in `listen'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/webrick-1.8.1/lib/webrick/server.rb:111:in `initialize'
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:47:in `initialize'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/handler/webrick.rb:38:in `new'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/handler/webrick.rb:38:in `run'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:327:in `start'
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.3/lib/rails/commands/server/server_command.rb:39:in `start'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.3/lib/rails/commands/server/server_command.rb:144:in `block in perform'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from <internal:kernel>:90:in `tap'
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.3/lib/rails/commands/server/server_command.rb:135:in `perform'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
foreman stdout | 10:09:53 web.1  | 	from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | 	from bin/rails:9:in `<main>'
foreman stdout | 
foreman stdout | 10:09:53 web.1  | exited with code 1
foreman stdout | 
foreman stdout | 10:09:53 system | sending SIGTERM to all processes
foreman stdout | 
foreman stdout | 10:09:58 system | sending SIGKILL to all processes
foreman stdout | 
2024-01-23 10:09:58,774 INFO exited: foreman (exit status 1; not expected)
2024-01-23 10:09:59,776 INFO reaped unknown pid 609 (terminated by SIGKILL)

**Comment by Colin-XKL** [comment]
上面日志主要报错是无法绑定到80端口，`bind': Permission denied - bind(2) for 0.0.0.0:80 (Errno::EACCES)`

我是用最新的 huginn 镜像和最新配置测试了下，没有复现你上面的这个问题。你本地使用的是否是最新的 docker 程序，是否是主流的 x86 Linux 发行版？需要提供更多的信息。

**Comment by Colin-XKL** [comment]
huginn 容器我默认设置的是在80端口提供服务，这样在 ttrss 中订阅来自huginn 的 rss 时，可以直接用 http 不用额外带上端口号。如果你本地环境比较特殊，80端口使用有问题的话，可以在环境变量中，将 `PORT`端口值更改为其他的，注意容器端口映射也需要改。

**Comment by caoliang12121** [comment]
> huginn 容器我默认设置的是在80端口提供服务，这样在 ttrss 中订阅来自huginn 的 rss 时，可以直接用 http 不用额外带上端口号。如果你本地环境比较特殊，80端口使用有问题的话，可以在环境变量中，将 `PORT`端口值更改为其他的，注意容器端口映射也需要改。

后来就是改到huginn的3000端口就可以了。感谢感谢

**Comment by caoliang12121** [comment]
> 上面日志主要报错是无法绑定到80端口，`bind': Permission denied - bind(2) for 0.0.0.0:80 (Errno::EACCES)`
> 
> 我是用最新的 huginn 镜像和最新配置测试了下，没有复现你上面的这个问题。你本地使用的是否是最新的 docker 程序，是否是主流的 x86 Linux 发行版？需要提供更多的信息。

跟着在问一个问题，ttrss里的代理是在哪里设置的，我想流量不要走clash，我的hub建在了vps上，但是clash我配置不好，导致现在ttrss无法更新。

**Comment by Colin-XKL** [comment]
> > 上面日志主要报错是无法绑定到80端口，`bind': Permission denied - bind(2) for 0.0.0.0:80 (Errno::EACCES)`
> > 我是用最新的 huginn 镜像和最新配置测试了下，没有复现你上面的这个问题。你本地使用的是否是最新的 docker 程序，是否是主流的 x86 Linux 发行版？需要提供更多的信息。
> 
> 跟着在问一个问题，ttrss里的代理是在哪里设置的，我想流量不要走clash，我的hub建在了vps上，但是clash我配置不好，导致现在ttrss无法更新。

ttrss 的环境变量里，HTTP_PROXY 这个变量是设置代理的，你把这一行删掉的话，再重新执行下docker compose up -d，ttrss 就不会使用代理了

**Comment by Colin-XKL** [comment]
位置是这里  https://github.com/Colin-XKL/RSSmanX/blob/6ee084de772407f93648f08d6f82587ba61f2492/rssman-ultimate/docker-compose.yml#L27

**Comment by caoliang12121** [comment]
> 位置是这里
> 
> https://github.com/Colin-XKL/RSSmanX/blob/6ee084de772407f93648f08d6f82587ba61f2492/rssman-ultimate/docker-compose.yml#L27

感谢！！
